/**
 * PDFMake Helper Functions
 *
 * This file contains utility functions for formatting data,
 * handling translations, and building common document elements.
 */

import type { Content, ContentText } from "pdfmake/interfaces";
import { bahtTextWithSymbol } from "@/lib/bahttext";

/**
 * Translation strings for Thai and English
 */
export const translations = {
  th: {
    // Quotation
    quotation: "ใบเสนอราคา",
    quotationNumber: "เลขที่",
    issueDate: "วันที่",
    validUntil: "ใช้ได้ถึง",

    // Invoice
    invoice: "ใบแจ้งหนี้ / ใบกำกับภาษี",
    invoiceNumber: "เลขที่",
    dueDate: "กำหนดชำระ",

    // Receipt
    receipt: "ใบเสร็จรับเงิน / ใบกำกับภาษี",
    receiptNumber: "เลขที่",
    paymentMethod: "วิธีชำระเงิน",
    receivedBy: "ผู้รับเงิน",
    signature: "ลายเซ็น",

    // Common
    company: "บริษัท",
    taxId: "เลขประจำตัวผู้เสียภาษี",
    address: "ที่อยู่",
    phone: "โทรศัพท์",
    email: "อีเมล",
    customer: "ลูกค้า",

    // Table headers
    no: "ลำดับ",
    description: "รายการ",
    quantity: "จำนวน",
    unit: "หน่วย",
    pricePerUnit: "ราคาต่อหน่วย",
    amount: "จำนวนเงิน",

    // Totals
    subtotal: "ยอดรวม",
    vat: "ภาษีมูลค่าเพิ่ม 7%",
    total: "รวมทั้งสิ้น",
    netTotal: "รวมทั้งสิ้น",
    totalInWords: "ตัวอักษร",
    baht: "บาท",

    // Bank details
    bankDetails: "รายละเอียดบัญชีธนาคาร",
    bankName: "ธนาคาร",
    accountNumber: "เลขที่บัญชี",
    accountName: "ชื่อบัญชี",

    // Other
    notes: "หมายเหตุ",
    date: "วันที่",
    paymentReceived: "ได้รับเงินเรียบร้อยแล้ว",

    // Footer
    computerGenerated: "เอกสารนี้ออกโดยระบบคอมพิวเตอร์",
  },
  en: {
    // Quotation
    quotation: "Quotation",
    quotationNumber: "No.",
    issueDate: "Date",
    validUntil: "Valid Until",

    // Invoice
    invoice: "Invoice / Tax Invoice",
    invoiceNumber: "No.",
    dueDate: "Due Date",

    // Receipt
    receipt: "Receipt / Tax Invoice",
    receiptNumber: "No.",
    paymentMethod: "Payment Method",
    receivedBy: "Received By",
    signature: "Signature",

    // Common
    company: "Company",
    taxId: "Tax ID",
    address: "Address",
    phone: "Phone",
    email: "Email",
    customer: "Customer",

    // Table headers
    no: "No.",
    description: "Description",
    quantity: "Qty",
    unit: "Unit",
    pricePerUnit: "Price/Unit",
    amount: "Amount",

    // Totals
    subtotal: "Subtotal",
    vat: "VAT 7%",
    total: "Total",
    netTotal: "Net Total",
    totalInWords: "In Words",
    baht: "Baht",

    // Bank details
    bankDetails: "Bank Details",
    bankName: "Bank",
    accountNumber: "Account No.",
    accountName: "Account Name",

    // Other
    notes: "Notes",
    date: "Date",
    paymentReceived: "Payment Received Successfully",

    // Footer
    computerGenerated: "This document is generated by computer system",
  },
};

/**
 * Get translated text
 */
export function t(
  key: keyof typeof translations.th,
  lang: "th" | "en" = "th",
): string {
  return translations[lang][key] || key;
}

/**
 * Format date to Thai or English format
 */
export function formatDate(
  date: Date | string,
  lang: "th" | "en" = "th",
): string {
  const d = typeof date === "string" ? new Date(date) : date;

  if (lang === "th") {
    return d.toLocaleDateString("th-TH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  }

  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/**
 * Format number with Thai or English locale
 */
export function formatNumber(num: number, lang: "th" | "en" = "th"): string {
  const locale = lang === "th" ? "th-TH" : "en-US";
  return num.toLocaleString(locale, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

/**
 * Format currency (same as formatNumber but explicit)
 */
export function formatCurrency(
  amount: number,
  lang: "th" | "en" = "th",
): string {
  return formatNumber(amount, lang);
}

/**
 * Convert amount to Thai Baht text
 */
export function formatBahtText(amount: number): string {
  return bahtTextWithSymbol(amount);
}

/**
 * Create a text element with style
 */
export function text(content: string, style?: string | string[]): ContentText {
  return {
    text: content,
    style: style,
  };
}

/**
 * Create a bold text element
 */
export function boldText(
  content: string,
  style?: string | string[],
): ContentText {
  return {
    text: content,
    bold: true,
    style: style,
  };
}

/**
 * Create company header section
 */
export function createCompanyHeader(
  company: {
    name: string;
    nameEn?: string | null;
    taxId: string;
    address: string;
    phone: string;
    email?: string | null;
    logo?: string | null;
  },
  lang: "th" | "en" = "th",
): Content {
  const companyName =
    lang === "th" ? company.name : company.nameEn || company.name;

  const content: Content[] = [{ text: companyName, style: "companyName" }];

  // Add English name if Thai is primary and English name exists
  if (lang === "th" && company.nameEn) {
    content.push({ text: company.nameEn, style: "companyDetails" });
  }

  content.push(
    { text: `${t("taxId", lang)}: ${company.taxId}`, style: "companyDetails" },
    {
      text: `${t("address", lang)}: ${company.address}`,
      style: "companyDetails",
    },
    { text: `${t("phone", lang)}: ${company.phone}`, style: "companyDetails" },
  );

  if (company.email) {
    content.push({
      text: `${t("email", lang)}: ${company.email}`,
      style: "companyDetails",
    });
  }

  const headerColumns: any[] = [
    {
      stack: content,
      width: "*",
    },
  ];

  // Add logo if exists
  if (company.logo) {
    headerColumns.push({
      image: company.logo,
      width: 80,
      height: 80,
      alignment: "right",
    });
  }

  return {
    columns: headerColumns,
    margin: [0, 0, 0, 20],
    columnGap: 20,
  };
}

/**
 * Create customer info section
 */
export function createCustomerSection(
  customer: {
    name: string;
    address: string;
    taxId?: string | null;
    phone?: string | null;
  },
  lang: "th" | "en" = "th",
): Content {
  const content: Content[] = [
    { text: t("customer", lang), style: "sectionTitle" },
    {
      table: {
        widths: [120, "*"],
        body: [
          [
            {
              text: `${t("company", lang)}:`,
              style: "infoLabel",
              border: [false, false, false, false],
            },
            {
              text: customer.name,
              style: "infoValue",
              border: [false, false, false, false],
            },
          ],
          [
            {
              text: `${t("address", lang)}:`,
              style: "infoLabel",
              border: [false, false, false, false],
            },
            {
              text: customer.address,
              style: "infoValue",
              border: [false, false, false, false],
            },
          ],
        ],
      },
      layout: "noBorders",
    },
  ];

  // Add optional fields in table
  const additionalRows: any[] = [];

  if (customer.taxId) {
    additionalRows.push([
      {
        text: `${t("taxId", lang)}:`,
        style: "infoLabel",
        border: [false, false, false, false],
      },
      {
        text: customer.taxId,
        style: "infoValue",
        border: [false, false, false, false],
      },
    ]);
  }

  if (customer.phone) {
    additionalRows.push([
      {
        text: `${t("phone", lang)}:`,
        style: "infoLabel",
        border: [false, false, false, false],
      },
      {
        text: customer.phone,
        style: "infoValue",
        border: [false, false, false, false],
      },
    ]);
  }

  if (additionalRows.length > 0) {
    (content[1] as any).table.body.push(...additionalRows);
  }

  return {
    stack: content,
    margin: [0, 0, 0, 15],
  };
}

/**
 * Create items table
 */
export function createItemsTable(
  items: Array<{
    id: string;
    description: string;
    quantity: number;
    unit: string;
    pricePerUnit: number;
    amount: number;
    subItems?: Array<{
      id: string;
      description: string;
    }>;
  }>,
  lang: "th" | "en" = "th",
): Content {
  const tableBody: any[] = [
    // Header row
    [
      { text: t("no", lang), style: "tableHeader", alignment: "center" },
      { text: t("description", lang), style: "tableHeader", alignment: "left" },
      { text: t("quantity", lang), style: "tableHeader", alignment: "center" },
      { text: t("unit", lang), style: "tableHeader", alignment: "center" },
      {
        text: t("pricePerUnit", lang),
        style: "tableHeader",
        alignment: "right",
      },
      { text: t("amount", lang), style: "tableHeader", alignment: "right" },
    ],
  ];

  // Data rows
  items.forEach((item, index) => {
    // Main item
    tableBody.push([
      { text: (index + 1).toString(), style: "tableCellCenter" },
      { text: item.description, style: "tableCell" },
      { text: formatNumber(item.quantity, lang), style: "tableCellCenter" },
      { text: item.unit, style: "tableCellCenter" },
      { text: formatNumber(item.pricePerUnit, lang), style: "tableCellRight" },
      { text: formatNumber(item.amount, lang), style: "tableCellRight" },
    ]);

    // Sub-items
    if (item.subItems && item.subItems.length > 0) {
      item.subItems.forEach((subItem) => {
        tableBody.push([
          { text: "", border: [true, false, true, false] },
          {
            text: `• ${subItem.description}`,
            style: "subItem",
            border: [true, false, true, false],
          },
          { text: "", border: [true, false, true, false] },
          { text: "", border: [true, false, true, false] },
          { text: "", border: [true, false, true, false] },
          { text: "", border: [true, false, true, false] },
        ]);
      });
    }
  });

  return {
    table: {
      headerRows: 1,
      widths: ["7%", "38%", "12%", "10%", "15%", "18%"],
      body: tableBody,
    },
    layout: {
      hLineWidth: (i, node) =>
        i === 0 || i === 1 || i === node.table.body.length ? 1 : 0.5,
      vLineWidth: () => 1,
      hLineColor: () => "#dddddd",
      vLineColor: () => "#dddddd",
      fillColor: (i) => (i === 0 ? "#333333" : i % 2 === 0 ? "#f9f9f9" : null),
    },
    margin: [0, 10, 0, 10],
  };
}

/**
 * Create summary table (subtotal, VAT, total)
 */
export function createSummaryTable(
  subtotal: number,
  vatAmount: number,
  total: number,
  lang: "th" | "en" = "th",
): Content {
  return {
    table: {
      widths: ["*", 120],
      body: [
        [
          {
            text: t("subtotal", lang),
            style: "summaryLabel",
            border: [false, false, false, true],
          },
          {
            text: formatCurrency(subtotal, lang),
            style: "summaryValue",
            border: [false, false, false, true],
          },
        ],
        [
          {
            text: t("vat", lang),
            style: "summaryLabel",
            border: [false, false, false, true],
          },
          {
            text: formatCurrency(vatAmount, lang),
            style: "summaryValue",
            border: [false, false, false, true],
          },
        ],
        [
          {
            text: t("total", lang),
            style: "totalLabel",
            border: [false, false, false, false],
          },
          {
            text: formatCurrency(total, lang),
            style: "totalValue",
            border: [false, false, false, false],
          },
        ],
      ],
    },
    layout: "noBorders",
    margin: [0, 20, 0, 0],
    alignment: "right",
  };
}

/**
 * Create bank details section
 */
export function createBankDetailsSection(
  bank: {
    bankName?: string | null;
    bankAccountNumber?: string | null;
    bankAccountName?: string | null;
  },
  lang: "th" | "en" = "th",
): Content | null {
  if (!bank.bankName) return null;

  const content: Content[] = [
    { text: t("bankDetails", lang), style: "bankDetailsTitle" },
    { text: `${t("bankName", lang)}: ${bank.bankName}` },
  ];

  if (bank.bankAccountNumber) {
    content.push({
      text: `${t("accountNumber", lang)}: ${bank.bankAccountNumber}`,
    });
  }

  if (bank.bankAccountName) {
    content.push({
      text: `${t("accountName", lang)}: ${bank.bankAccountName}`,
    });
  }

  return {
    stack: content,
    style: "bankDetailsBox",
    margin: [0, 20, 0, 0],
  };
}

/**
 * Create notes section
 */
export function createNotesSection(
  notes: string,
  lang: "th" | "en" = "th",
): Content {
  return {
    stack: [{ text: t("notes", lang), style: "notesTitle" }, { text: notes }],
    style: "notesBox",
    margin: [0, 20, 0, 0],
  };
}

/**
 * Create footer with centered text
 */
export function createFooter(lang: "th" | "en" = "th"): Content {
  const thaiText = t("computerGenerated", "th");
  const englishText = t("computerGenerated", "en");

  return {
    text: `${thaiText} / ${englishText}`,
    style: "footer",
    margin: [0, 30, 0, 0],
  };
}
